import { createStore } from 'vuex'

export default createStore({
  state: {
    skills: [
      "All Skills",
      "Generalist lawyer",
      "Family, personal and consumer law",
      "Real estate law, leases, construction, neighborhood",
      "Labor law and social security law",
      "Business law, contracts, and commercial companies",
      "NICT law, IT, advertising and intellectual property",
      "Insurance, bodily injury and health law",
      "Public law, urban planning and environmental law",
      "International law, foreigners law and immigration",
      "Criminal law, traffic law",
      "Tax law, taxes, duties",
      "Administrative law",
    ],
    cities: [
      "Casablanca",
      "El Kelaa des Srarhna",
      "Fès",
      "Tangier",
      "Marrakech",
      "Sale",
      "Rabat",
      "Meknès",
      "Kenitra",
      "Agadir",
      "Oujda-Angad",
      "Tétouan",
      "Taourirt",
      "Temara",
      "Safi",
      "Laâyoune",
      "Mohammedia",
      "Kouribga",
      "Béni Mellal",
      "El Jadida",
      "Ait Melloul",
      "Nador",
      "Taza",
      "Settat",
      "Barrechid",
      "Al Khmissat",
      "Inezgane",
      "Ksar El Kebir",
      "Larache",
      "Guelmim",
      "Khénifra",
      "Berkane",
      "Bouskoura",
      "Al Fqih Ben Çalah",
      "Oued Zem",
      "Sidi Slimane",
      "Errachidia",
      "Guercif",
      "Oulad Teïma",
      "Ad Dakhla",
      "Ben Guerir",
      "Wislane",
      "Tiflet",
      "Lqoliaa",
      "Taroudannt",
      "Sefrou",
      "Essaouira",
      "Fnidq",
      "Ait Ali",
      "Sidi Qacem",
      "Tiznit",
      "Moulay Abdallah",
      "Tan-Tan",
      "Warzat",
      "Youssoufia",
      "Martil",
      "Aïn Harrouda",
      "Skhirate",
      "Ouezzane",
      "Sidi Yahya Zaer",
      "Benslimane",
      "Al Hoceïma",
      "Beni Enzar",
      "M’diq",
      "Sidi Bennour",
      "Midalt",
      "Azrou",
      "Ain El Aouda",
      "Beni Yakhlef",
      "Semara",
      "Ad Darwa",
      "Al Aaroui",
      "Qasbat Tadla",
      "Boujad",
      "Jerada",
      "Chefchaouene",
      "Mrirt",
      "Sidi Mohamed Lahmar",
      "Tineghir",
      "El Aïoun",
      "Azemmour",
      "Temsia",
      "Zoumi",
      "Laouamra",
      "Zagora",
      "Ait Ourir",
      "Sidi Bibi",
      "Aziylal",
      "Sidi Yahia El Gharb",
      "Biougra",
      "Taounate",
      "Bouznika",
      "Aourir",
      "Zaïo",
      "Aguelmous",
      "El Hajeb",
      "Mnasra",
      "Mediouna",
      "Zeghanghane",
      "Imzouren",
      "Loudaya",
      "Tit Mellil",
      "Asilah",
      "Demnat",
      "Arfoud",
      "Sidi Smai’il",
      "Taza",
      "Aïn Taoujdat",
      "Chichaoua",
    ],
  },
  getters: {
  },
  mutations: {
  },
  actions: {
  },
  modules: {
  }
})
